-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 14:56:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uz4684_univ_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uz4684_univ_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uz4684_univ_db` DEFAULT CHARACTER SET utf8 ;
USE `uz4684_univ_db` ;

-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Student` (
  `first_name` VARCHAR(45) NOT NULL,
  `student_number` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `year_admittance` DATETIME NOT NULL,
  `birthday` DATETIME NOT NULL,
  `department_number` INT NOT NULL,
  PRIMARY KEY (`student_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Professor` (
  `professor_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `office_room` INT NOT NULL,
  `start_office_hours` INT NOT NULL,
  `end_office_hours` INT NOT NULL,
  `department_number` INT NOT NULL,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Depratment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Depratment` (
  `department_number` INT NOT NULL,
  `department_name` VARCHAR(45) NOT NULL,
  INDEX `fk_Depratment_Professor1_idx` (`department_number` ASC) VISIBLE,
  CONSTRAINT `fk_Depratment_Professor1`
    FOREIGN KEY (`department_number`)
    REFERENCES `uz4684_univ_db`.`Professor` (`department_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Depratment_Student1`
    FOREIGN KEY (`department_number`)
    REFERENCES `uz4684_univ_db`.`Student` (`department_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Enrollment` (
  `course_number` INT NOT NULL,
  `student_number` VARCHAR(45) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `section` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Courses` (
  `course_number` INT NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  INDEX `fk_Courses_Enrollment_idx` (`course_number` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Enrollment`
    FOREIGN KEY (`course_number`)
    REFERENCES `uz4684_univ_db`.`Enrollment` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`Classes` (
  `class_number` INT NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `year` DATETIME NOT NULL,
  `professor` VARCHAR(45) NOT NULL,
  `day` DATETIME NOT NULL,
  `duration` DATETIME NOT NULL,
  `class_hours` DATETIME NOT NULL,
  PRIMARY KEY (`class_number`),
  INDEX `fk_Classes_Student1_idx` (`year` ASC) VISIBLE,
  CONSTRAINT `fk_Classes_Student1`
    FOREIGN KEY (`year`)
    REFERENCES `uz4684_univ_db`.`Student` (`year_admittance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uz4684_univ_db`.`FinalGrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uz4684_univ_db`.`FinalGrade` (
  `course_number` INT NOT NULL,
  `student_number` INT NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `year` DATETIME NOT NULL,
  `grade` ENUM('A', 'B', 'C', 'D', 'F') NOT NULL,
  `section` VARCHAR(45) NOT NULL,
  INDEX `fk_FinalGrade_Courses1_idx` (`course_number` ASC) VISIBLE,
  INDEX `fk_FinalGrade_Classes1_idx` (`semester` ASC) VISIBLE,
  INDEX `fk_FinalGrade_Classes2_idx` (`year` ASC) VISIBLE,
  CONSTRAINT `fk_FinalGrade_Courses1`
    FOREIGN KEY (`course_number`)
    REFERENCES `uz4684_univ_db`.`Courses` (`course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FinalGrade_Classes1`
    FOREIGN KEY (`semester`)
    REFERENCES `uz4684_univ_db`.`Classes` (`semester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FinalGrade_Classes2`
    FOREIGN KEY (`year`)
    REFERENCES `uz4684_univ_db`.`Classes` (`year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
